### PR TITLE
This should work.

### PR DESCRIPTION
**Pull request by sa-webb**
I changed the deploy command in the package.json, added an index.html file at the root that points to the index.html public folder and removed the README. With that being said, execute `npm run deploy` and then change the GH Pages repository settings to deploy from the master branch to the gh-pages branch.

### CODE REVIEW

**Comment by willjrowe** [comment]
@sa-webb Awesome thank you I think I'm getting closer, but I'm running into this error now:

fatal: A branch named 'gh-pages' already exists.

npm ERR! code ELIFECYCLE
npm ERR! errno 1

I'm going to try re-cloning my repo and re-installing the relevant packages. Let me know if you have any thoughts

**Comment by sa-webb** [comment]
William, my fault - since you merged the pull request then the branch and changes already exist. So disregard executing the command and simply try changing the settings of the repo.

**Comment by willjrowe** [comment]
If I change `npm run deploy` to `gatsby build --prefix-paths && gh-pages -d public -b newBranch`

The process just hangs

**Comment by willjrowe** [comment]
Sorry didnt see your newest comment I'll take a look at that now @sa-webb

**Comment by willjrowe** [comment]
I currently don't have a ghpages branch should I be manually creating it?

**Comment by sa-webb** [comment]
Yes. Create it manually and then I will create a pull request from my gh-pages to your gh-pages

**Comment by sa-webb** [comment]
Give me a sec - running into this issue now. "You’ll need to use two different branch names to get a valid comparison." I will change mine. We are going to get this to work lol

**Comment by willjrowe** [comment]
Done and changed in settings to deploy from gh-pages branch

**Comment by willjrowe** [comment]
Hmm yeah not sure what that error is about lol but thank you

**Comment by sa-webb** [comment]
This is hilarious.. So the gh-pages only builds to a gh-pages branch. Can you switch to your branch - remove all of the files of that branch and then push it back so that it is empty. Otherwise we are going to have to figure out how to get that command to execute on your end.

**Comment by sa-webb** [comment]
Also, in the meantime - if you'd like to preview it here's my version https://sa-webb.github.io/IR-Plan-Site/

**Comment by willjrowe** [comment]
Lol love your version that's exactly what I'm hoping for. So I deleted the gh-pages branch on GitHub should I try and re-make it completely empty or just let gh-pages package handle that.

**Comment by sa-webb** [comment]
I can't believe the process hangs on your end, it's almost as if you aren't authorized for it to publish. Anyways, try this command to create the empty branch `git checkout --orphan gh-pages` and hopefully I can pull request into it this time.

**Comment by sa-webb** [comment]
Also you may want to push it to remote so that it shows up on GitHub

**Comment by willjrowe** [comment]
Ok will do sorry I messed up my local branches a bit so it might take me a second to sort it all out

**Comment by sa-webb** [comment]
I see the gh-pages branch again with the same contents so I'll assume it isn't letting you create the branch as empty. However its contents are too different for me to try to PR to it. Just let me know when you are able get it empty. In the meantime, are you using the CLI to push to GitHub? If so, make sure it is configured to your account like so - https://stackoverflow.com/questions/37398524/how-do-i-check-my-github-settings-or-who-im-signed-in-as-on-my-current-project

**Comment by willjrowe** [comment]
Yeah my local is a mess so I cloned your fork into a new repo here: https://github.com/willjrowe/IR-Plan-Page
I'm messing around with it now, I'll open an issue depending on what happens

**Comment by willjrowe** [comment]
@sa-webb take a look at this whenever you get the chance thanks again so much

https://github.com/willjrowe/IR-Plan-Page/issues/1

**Pull request closed without merging**
